# -*- coding: utf-8 -*-
"""ProphetStockPredictions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uTxv3xp48CC2vibpyiUoDO8EmYXLPurz
"""

!pip install pystan~=2.14

import yfinance
import datetime as dt

start = dt.datetime(2020,1,1)
end = dt.datetime.now()
data = yfinance.download("TSLA", start, end)

data.to_csv("Stock_data.csv")

import pandas as pd
data = pd.read_csv("Stock_data.csv")

data = data[["Date","Close"]]

data.columns = ["ds", "y"]

data

from prophet import Prophet

prophet = Prophet(daily_seasonality=True)
prophet.fit(data)

future_dates = prophet.make_future_dataframe(periods=365)
predictions = prophet.predict(future_dates)

from prophet.plot import plot_plotly

plot_plotly(prophet, predictions)

unknown_data = data.iloc[-90:]
data = data.iloc[:-90]

prophet = Prophet(daily_seasonality=True)
prophet.fit(data)

future_dates = (prophet.make_future_dataframe(periods=365))
predictions = prophet.predict(future_dates)

plot_plotly(prophet, predictions)

import matplotlib.pyplot as plt

plt.figure(figsize=(12,8))


pred = predictions[predictions['ds'].isin(unknown_data['ds'])]

plt.plot(pd.to_datetime(unknown_data['ds']), unknown_data['y'], label="Actual")
plt.plot(pd.to_datetime(unknown_data['ds']), pred['yhat'], label="Prediction")

plt.legend()